
# html lang
language: zh-CN

# main menu navigation
menu:
  首页: /
  归档: /archives
  关于: /about
  More links: /...
  友链: /friends
  个人简历: /vc
  摄影作品: /gallery

# main logo in navigation
logo: /images/logo.svg

# cove description
description: '域名变更提示：hikc.net(原) ---> jkc.icu(新)'

# cove icon
icon: /images/icon.png

# stylesheets loaded in the <head>
stylesheets:
- /css/screen.css

# scripts loaded in the end of the body
scripts:
- /js/main.js
- /js/lib/owl.carousel.min.js
- /js/lib/jquery.fitvids.js
- /js/lib/lazysizes.min.js
- /js/lib/infinite-scroll.pkgd.min.js
- /js/lib/busuanzi.pure.mini.js
- /js/search.js

# comments
comments:
  # Disqus comments
  disqus_shortname: hikc

# formspree
endpoint: https://formspree.io/f/mrgrjbpj
