
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Archives: /archives
  About: /about
  More links: /...
  Contact: /contact

# main logo in navigation
logo: /images/logo.svg

# cove description
description: '域名变更提示：hikc.net(原) ---> jkc.icu(新)'

# cove icon
icon: /images/icon.png

# stylesheets loaded in the <head>
stylesheets:
- /css/screen.css

# scripts loaded in the end of the body
scripts:
- /js/main.js
- /js/lib/owl.carousel.min.js
- /js/lib/jquery.fitvids.js
- /js/lib/lazysizes.min.js
- /js/lib/infinite-scroll.pkgd.min.js
